kind: PersistentVolume
apiVersion: v1
metadata:
  name: jupyter-pv
  namespace: jupyter-ns
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/jitsejan/mnt/data"
