kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jupyter-pvc
  namespace: jupyter-ns
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
