kind: PersistentVolume
apiVersion: v1
metadata:
  name: r-studio-pv
  namespace: r-studio-ns
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/jitsejan/mnt/rstudiodata"
