kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: r-studio-pvc
  namespace: r-studio-ns
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
