apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  creationTimestamp: null
  name: tenant1
  namespace: minio-operator
scheduler:
  name: ""
spec:
  certConfig: {}
  console:
    consoleSecret:
      name: tenant1-console-secret
    image: minio/console:v0.6.3
    replicas: 2
    resources: {}
  credsSecret:
    name: tenant1-creds-secret
  image: minio/minio:RELEASE.2021-03-01T04-20-55Z
  imagePullSecret: {}
  mountPath: /export
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - tenant1
          topologyKey: kubernetes.io/hostname
    resources: {}
    servers: 2
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: default
      status: {}
    volumesPerServer: 2
  requestAutoCert: true
status:
  availableReplicas: 0
  certificates: {}
  currentState: ""
  pools: null
  revision: 0
  syncVersion: ""

---
apiVersion: v1
data:
  accesskey: OTliNzhjNjEtNDI1Zi00NTY1LWEzNzItMDRiYTAzMTlhMDNk
  secretkey: OTNjOTE4YzEtYmFhOC00MzYzLTk2NDktYWMyZWYzYjVkMGM4
kind: Secret
metadata:
  creationTimestamp: null
  name: tenant1-creds-secret
  namespace: minio-operator

---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: YWRtaW4=
  CONSOLE_PBKDF_PASSPHRASE: ZDZhMGY1YTEtMzk3Ny00YjZkLTk4OTYtNGI3NGRjYTk5Y2I3
  CONSOLE_PBKDF_SALT: MDdjN2ZmYjMtNmJiYy00MzQyLThiNTItYjRiZmMzZjYxZjVh
  CONSOLE_SECRET_KEY: M2ExN2YwNjktY2RmYS00NjQ1LTkwMTUtM2RlNTI0YzViZTBj
kind: Secret
metadata:
  creationTimestamp: null
  name: tenant1-console-secret
  namespace: minio-operator

